version:  '3.8'
services:
    nginx:
      build:
        context: Dockers\nginx
        dockerfile: Dockerfile
        args:
          - APP_ENV=PROD
          - DB_HOST=mysql-db
          - DB_USER=root
          - DB_PWD=root
          - DB_NAME=sendme
          - DB_PORT=3306
          - DB_VERSION=5.7
          - DB_DRIVER=pdo_mysql
      image: php/7.4.11-fpm-alpine3.12
      ports:    
        - "80:80"
    mysql-db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root