version:  '3.8'
services:
    nginx:
      build:
        context: Dockers/nginx
        dockerfile: Dockerfile
        args:
          - APP_ENV=prod
          - DB_HOST=namesend-mysql
          - DB_USER=root
          - DB_PWD=root
          - DB_NAME=namesend
          - DB_PORT=3306
          - DB_VERSION=5.7
          - DB_DRIVER=pdo_mysql
          - GOOGLE_CLIENT_ID=YOUR_CLIENT_ID
          - GOOGLE_CLIENT_SECRET=YOUR_SECRET
          - AZURE_CLIENT_ID=YOUR_CLIENT_ID
          - AZURE_CLIENT_SECRET=YOUR_SECRET
      image: php/7.4.11-fpm-alpine3.12
      ports:
        - "8084:80"
      depends_on:
        - mysql-db
      container_name: namesend-web
    volumes:
      - /certs/domain.tld:/etc/nginx/certs/
    mysql-db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
      container_name: namesend-mysql