version:  '3.8'
services:
    nginx:
      restart: always
      build:
        context: Dockers\nginx
        dockerfile: Dockerfile
      image: nginx/alpine
      volumes:
        - './../../public/:/usr/src/app'
        - './Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      ports:    
        - "80:80"
      depends_on:
        - php-fpm
    php-fpm:
      build:
        context: Dockers\php-fpm
        dockerfile: Dockerfile
      restart: on-failure
      ports:
        - "9000:9000"
      volumes:
        - '.:/usr/src/app' 