version:  '3.8'
services:
    nginx:
      build:
        context: Dockers\nginx
        dockerfile: Dockerfile
        args:
          - APP_ENV=PROD
          - DB_HOST=172.29.0.1
          - DB_USER=root
          - DB_PWD=root
          - DB_NAME=sendme
          - DB_PORT=3306
          - DB_VERSION=5.7
      image: php/7.4.11-fpm-alpine3.12
      ports:    
        - "80:80"