login_check:
    path: /login_check

app_logout:
    path: /logout
    methods: GET

indice:
    path:       /{_locale}
    controller: App\Controller\IndexController::index
    requirements:
            _locale: en|es